if: commit_message =~ ^Release v$

matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      language: node_js
      node_js: "14"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    export CERTIFICATE_P12=cert.p12;
    echo $MACOS_CERT_P12 | base64 --decode > $CERTIFICATE_P12;
    export KEYCHAIN=build.keychain;
    security create-keychain -p travis $KEYCHAIN;
    security default-keychain -s $KEYCHAIN;
    security unlock-keychain -p travis $KEYCHAIN;
    security import $CERTIFICATE_P12 -k $KEYCHAIN -P $MACOS_CERT_PASSWORD -T /usr/bin/codesign 2>&1 >/dev/null;
    rm $CERTIFICATE_P12;
    yarn run publish
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  